### ISSUE TITLE
we need a logo

### ISSUE THREAD

**Issue by Leprevost** [BioDocker/biodocker#11]
I think it would be great if we had a custom logo for this project.

**Comment by ypriverol** [comment]
@BioDocker/contributors  any contributor that can help with the design.. in my opnion we should try to keep most of the current docker part but adding something from bioinfo. @rajido

**Comment by lgatto** [comment]
Keeping the whale but replacing or labelling the boxes with bio-related images such as, for examples A, C, G, T's, might be interesting to explore.

**Comment by Leprevost** [comment]
I was thinking about that lately, at first i thought about substituting the
boxes for a spectrogram or something like that, but I think it would be
better to have something 'biological', without making reference to a
specific area like genomics or proteomics...

**Comment by sauloal** [comment]
a tree?

**Comment by Leprevost** [comment]
a tree sounds good (white tree of Gondor, maybe? =D). Just don't know how
to put a tree on top a whale, hehe

**Comment by bgruening** [comment]
Oh I like the idea of a tree!
https://www.google.de/search?q=bonsai&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMItZnovtG5xwIVAlYUCh2rnAO9&biw=1600&bih=999#q=bonsai&tbs=itp:clipart,sur:fmc&tbm=isch

TreeHugger!

**Comment by percolator** [comment]
It might be nice if you did not restrict to a single species. What if the
whale could carried Noah's ark?

On Fri, Aug 21, 2015 at 9:21 AM, Björn Grüning <notifications@github.com>
wrote:

> Oh I like the idea of a tree!
>
> https://www.google.de/search?q=bonsai&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAWoVChMItZnovtG5xwIVAlYUCh2rnAO9&biw=1600&bih=999#q=bonsai&tbs=itp:clipart,sur:fmc&tbm=isch
>
> TreeHugger!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BioDocker/biodocker/issues/11#issuecomment-133313714>.
>



-- 
========================
Lukas Käll
http://kaell.org

**Comment by Leprevost** [comment]
please, no religious references.

**Comment by Leprevost** [comment]
updates on #33
