### ISSUE TITLE
Create a HOW to contribute Page

### ISSUE THREAD

**Issue by ypriverol** [BioDocker/biodocker#13]
@BioDocker/contributors  We should Create a HOW to contribute Page in the BioDocker.

**Comment by sauloal** [comment]
Usually a pull request would be a nice idea. What do you think?

**Comment by bgruening** [comment]
PR are only a small portion of what makes a good contribution. I would recommend to take over large portions of this one: https://github.com/galaxyproject/galaxy/blob/dev/CONTRIBUTING.md

It served us well so far and is a good compromise of high-quality contributions but keep the barrier to contribute low.

**Comment by sauloal** [comment]
@bgruening , very good link. I haven't thought it in so many details. My view was, in doing a PR there are fields where the contributor can explain itself and open discussion. I don't know whether specific rules are needed on how to do that. As I see, we could just copy/link those rules from galaxy. They seem reasonable enough.

**Comment by lgatto** [comment]
I think that a specific 'How to contribute' page would be very beneficial. Even if, in the end, the only technical step is a PR, such a page would go a long way to make possible contributors to know what is really expected from them in terms of documentation, maintenance, ... it's a gateway to the BioDocker community.

**Comment by ypriverol** [comment]
Agree with a CONTRIBUTING.md. I will create it in this repository based in other projects such as Galaxy and Biojs projects. If you are agree @sauloal @lgatto @bgruening @BioDocker/contributors  I will close this issue.

**Comment by bgruening** [comment]
:+1:  to everything what @lgatto said!
@ypriverol can we close it when this document exist?

**Comment by ypriverol** [comment]
I will create it today and then we can close the issue.

**Comment by Leprevost** [comment]
do you prefer to have a separate file/repor for that, or to use the wiki we
have at the specifications repository?

**Comment by sauloal** [comment]
@bgruening , I agree on closing it.
@Leprevost , my experience is that using the wiki us much better than creating files / repositories. besides being a git repository in itself, it allows for commenting. Also, we can heavily edit it without creating a myriad of commits in the main repository, keeping it cleaner

**Comment by ypriverol** [comment]
As we agree I will close this issue.
