### ISSUE TITLE
should only LTS base OS be used?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#16]
should only LTS base OS (when available) be used?

**Comment by bgruening** [comment]
I would even go further and would like to see that we strongly recommend **one** base OS. This will improve the usability of our containers dramatically.

I'm voting for latest debian stable.

**Comment by Leprevost** [comment]
I agree with using one stable version for the images, like debian stable

**Comment by sauloal** [comment]
I agree. besides usability, download sizes would also be reduced.
if not a stretch, some help could be given on how to clean the apt cache which also can take quite some space

**Comment by sauloal** [comment]
@bgruening , i've been thinking. one OS would not be ideal. there are programs which are made to RPM flavours and not DEB. a small and controlled set would be more appropriated. and better still, if someone manages to use busybox of coreOS, who are we to complain about a 80% reduction in footprint? :D

**Comment by bgruening** [comment]
@sauloal I would like to try to use vendor independent package formats, or compile by our own. RPM vs. DEB was holding us back too long. GUIX, linux-brew, pip, conda ... 

I would argue the other way around, if you already have one BioDocker container, taking a BusyBox based one will force you to download 20% more ;)

**Comment by sauloal** [comment]
@bgruening , I agree that RPM/DEB is a pain. but some packages might only provide one flavour and I don't think it would be wise to forbid either way. That said, it could be added as a excellent practice to try to use the same base

**Comment by bgruening** [comment]
Couldn't we simply compile it from scratch? I actually did not expect to have so many up-to-date packages as RPM/DEB. We can deal with this case as soon as it arise, isn't it?

**Comment by sauloal** [comment]
@bgruening Yes. Completely. But I think those open discussions are important because they will serve as base to the confection of the CONTRIBUTING document, the GOOD PRACTICES and the general policies of acceptance of pull requests.

**Comment by bgruening** [comment]
Sure! What about a `best practices` guide to emphasize the usage of debian stable. In rare cases we will allow other distributions and this is decided per case?

**Comment by sauloal** [comment]
@bgruening , that's has already been assigned to me ( see #8 ) and I'm gathering information (through opening new issues). But I won't have time to consolidate this for a few weeks. 
When I do I have all this discussion to remember our agreements and refer to.

**Comment by sauloal** [comment]
fixed
