### ISSUE TITLE
dockerfile template missing repository name and how to build it

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#21]
I propose that the dockerfile template, in my view, needs to require the name to which the image should be registered (e.g.: biodocker/progam1) as one of the header informations

Also, it should contain the build command (e.g.: docker build biodocker/program1 .)

**Comment by Leprevost** [comment]
I agree, we can add that to the template. I will update the wiki page.

**Comment by ypriverol** [comment]
@Leprevost when you adde this to the template please close the issue.

**Comment by sauloal** [comment]
fixed
