### ISSUE TITLE
dev dockerhub channel

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#22]
I propose that, once new pull requests will be added to the dev channel (as described in the contributting.md) , we should have a separated dev channel on dockerhub so that the dev and stable do not mix

**Comment by Leprevost** [comment]
I don't rhink dockerhub works with tracks or channels like github does, I
think we could use a separate account for beta containers.

**Comment by sauloal** [comment]
@Leprevost . yes. dockerhub automatic builds does work with 
![untitled](https://cloud.githubusercontent.com/assets/506579/9399969/b95e12c6-47e5-11e5-9559-a988d053dbc8.png)

**Comment by Leprevost** [comment]
yeah I know, we have been using that since the beginning, all the
containers are also available on dockerhub in a account called biodckr

**Comment by sauloal** [comment]
the question is, should we have a separated git repo for dev or a dev branch?
the contribution manual says the second

**Comment by Leprevost** [comment]
i think a dev branch would be better

**Comment by sauloal** [comment]
I wonder. In the dev channel we would have several "packages" at the same time. How would we promote only one of the packages without meeting the whole Dev branch?

**Comment by Leprevost** [comment]
Ok i was thinking better about this issue and it may be better to have a different repository called sandbox where new projects could be created and testes before moving to the main repo list. having separated branches could complicate things in a way we don't need now.

**Comment by sauloal** [comment]
might be better but must be reflected on the contributing.md
