### ISSUE TITLE
should we have our own base image?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#23]
Should be have our own base image?
Although not of compulsory usage, we could provide a image always updated (monthly?) and containing the helper scripts (help, version, etc) inside?

Users could use:
```FROM biodocker/biodocker:latest```

and have the latest ubuntu LTS with all updates already installed and apt cache cleaned.

complementary we could have a biodocker/biodockerdev containing gcc , biodocker/biodockerjava containing java, etc

**Comment by ypriverol** [comment]
This is actually a fantastic idea. Can we add this to the specification and work in how we will do the release based, monthly, daily basis or other systems like every 6 months. @sauloal

**Comment by Leprevost** [comment]
Hum, but what we would do differently from the base images to justify having a specific one just for us? I tend to prefer maintaining the use of the 'traditional" base images unless we have some strong motive for doing so.

**Comment by sauloal** [comment]
@Leprevost , keep it updated (apt-get update, apt-get upgrage, apt-get clean, apt-get purge)

**Comment by Leprevost** [comment]
OK, sounds good, how do you plan to do that? should we just get a stable Debian and rename it?

**Comment by sauloal** [comment]
either debian or ubuntu. debian is smaller but im not sure they have an functional LTS system

**Comment by Leprevost** [comment]
i think we can
https://wiki.debian.org/LTS/Using

**Comment by sauloal** [comment]
seems more complicated than using ubuntu :)

**Comment by Leprevost** [comment]
yes I agree, that's why I was using Ubuntu since the beginning

**Comment by Leprevost** [comment]
I just finished building our own base image/ Its based on Ubuntu 14.04:latest and its called just biodocker.

I pushed the Dockerfile instructions so you all can see how this is done, check here: 
https://github.com/BioDocker/containers/tree/master/base

In order to use this base image we need to do the following change in Dockerfiles:

before:

`FROM ubuntu:latest`

to

`FROM biodckr/biodocker:latest`

The image is also hosted on dockerhub, but I'm not using the automatic build system, because we need to keep this image updated.

**Comment by sauloal** [comment]
Nice!

You can put it on automatic build and trigger the build manually in dockerhub if you prefer. the advantage is that it becomes a "trusted" image

Also,

I guess it would be nice to transfer all that I put in the dockerfile template there (user creation, update, clean of apt) so that users just need to change to root, install what they need and change back to biodocker user. reducing error

**Comment by Leprevost** [comment]
was thinking in handling this image manually, but we can do that too, Im going to set the build now to see how it goes

**Comment by Leprevost** [comment]
done, the base image now is under an automated build, already available to download
