### ISSUE TITLE
Should we allow privileged containers? docker inside docker?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#24]
A security issue.

To make things simpler to some applications, the user can have privileged containers and docker inside docker.

Should this be allowed despite the risk?

Docker inside docker is really useful to package databases and code in a single image.
It can be done by calling the host's docker (right way) or by installing docker inside the image (wrong way).

**Comment by Leprevost** [comment]
I think for now we should not allow or promote the use of docker inside
docker. We have to think also in people trying to run these images inside
clusters and larger infrastructures. If we allow something with a certain
degree of risk, certainly, sysadmins will not allow the use of it on their
systems.

**Comment by sauloal** [comment]
perfect. my idea exactly.

That said, running docker is never "safe". anyone who can run docker can use -v/:/data and change any settings of the host computer. :D

**Comment by ypriverol** [comment]
Can we close @sauloal? and perhaps include an sentence in the specification about it?

**Comment by sauloal** [comment]
@ypriverol , I think we could close it but I like to leave the questions open for at least one week so that other members can have the chance of voicing their opinion.

I'm aware that I'm using "issues" as a replacement for a forum :D
