### ISSUE TITLE
One folder for each version?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#26]
from the wiki:
https://github.com/BioDocker/biodocker/wiki/Project-organization

> Inside, each version of the software will have its own directory containing the Dockerfile and the necessary files.

this will force us to, when setting the autobuild from dockerhub, create a different image for each version instead of creating a different tag for each version.

e.g.:
```
https://github.com/BioDocker/containers/blob/master/Comet/2014011/Dockerfile -> biodockr/comet2014011:latest
```

instead of:

```
https://github.com/BioDocker/containers/blob/master/Comet/2014011/Dockerfile -> biodockr/comet:2014011
```

**Comment by sauloal** [comment]
@BioDocker/contributors any input?

**Comment by Leprevost** [comment]
Sorry, I don't understand what is wrong with the current set up. We are using different folders for each version and in the docker hub account we have a repository for each software. Inside this repository, different tags are set for each version. You can try the following, for example:

`docker pull biodckr/comet:2014011`

**Comment by bgruening** [comment]
@sauloal I think your assumption is wrong. You can create image tags from folders if you like.

**Comment by sauloal** [comment]
@bgruening I see. 

But again, why would we create different folders?
If I modify a Dockerfile it is upgrade the program's version.
If I rebuild the image using the same dockerfile, it is to upgrade the underlying OS.

In the first case, the tag of the image should change.
In the same came, the tag of the image should also change but it can't once it is "fixed" to the program's version.

For example.
ubuntu 14.0.3  + program v1 = folder /program/v1/Dockerfile = tag "v1"
ubuntu 14.0.3  + program v2 = folder /program/v2/Dockerfile = tag "v2"
ubuntu 14.0.4  + program v1 = folder /program/v2/Dockerfile = tag "v1" CONFLICT
ubuntu 14.0.4  + program v2 = folder /program/v2/Dockerfile = tag "v1" CONFLICT

Besides, unless we plan to keep several versions of a program "updated" instead of "stored for historical reasons", there's no need to keep all the dockerfile versions ever created.

**Comment by prvst** [comment]
The folders are helpful only because of the DockerHub registry setup. The automated build need a folder with the given Dockerfile. I'm not sure there is a different way of doing.
