### ISSUE TITLE
goals for publication

### ISSUE THREAD

**Issue by prvst** [BioDocker/biodocker#29]
I think we should define some goals for the publication, lets define them here and so we can accelerate this process.

**Comment by Leprevost** [comment]
@BioDocker/contributors If you are interested in participate the paper writing, please send me your e-mail (preferably Gmail), so I can add you to the Google Docs file.

**Comment by bgruening** [comment]
* rising awareness of the projects
* defining project goals
* talking about standards
* process description
* describing use cases (e.g. Galaxy as consumer to automatically resolve tool dependencies)

**Comment by sauloal** [comment]
@bgruening can you explain your last point?

**Comment by ypriverol** [comment]
@bgruening can we push with galaxy to have the repo for the binaries, the way that we are now working is with releases in git and this is not acceptable and scalable.

**Comment by bgruening** [comment]
An advanced use case for example is that you give just a basic description to Galaxy or similar workflow engines, like `samtools in version 1.2`. This should be enough to automatically figure the dependency out, download the image from biodocker, run it and collect the results.

@ypriverol  I will be in November in the USA and will discuss this face to face if this is fast enough for you?

**Comment by ypriverol** [comment]
That would be ideal.. In any case if you need any support from our side, just let us to know.
