### ISSUE TITLE
Move containers to containers2 and create a new containers repository

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#30]
Currently the containers repository is 300Mb since it contains 'traces' of the old binaries. 

O propose to move containers to containers2 (for historical reasons) and create a new containers repository only with the dockerfiles.

/cc @BioDocker/contributors

**Comment by Leprevost** [comment]
so this 'containers 2' would act as an old repository or a repository for
unused things?

**Comment by sauloal** [comment]
My idea is that it would be an old repository and would be deleted after a while
unused/problematic things would be the sandbox i guess
