### ISSUE TITLE
I'm not an artist, but what about this logo?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#33]
![Logo](https://www.dropbox.com/s/ec1w1cbzriyicff/docker_logo.png?dl=1)
Or a shorter version
![Logo](https://www.dropbox.com/s/bpajg3qhi4fdp3p/docker_logo_2.png?dl=1)
/cc @BioDocker/contributors

**Comment by lgatto** [comment]
I think it looks good. 

In the original logo, the boxes contain stripes. Could we possibly add 0 and 1s, A, C, G, and Ts and/or amino acid letters?

By the way, what are docker's policies regarding re-using their logo?

**Comment by ypriverol** [comment]
@sauloal  I will prefer to make the tree thinner.

**Comment by sauloal** [comment]
@lgatto this is the logo of their gravatar (https://hub.docker.com/u/library/ )

Also, according to their [legal terms](https://www.docker.com/brand-guidelines) we are not even allowed to use the name docker in our repository. Also not allowed to use their icon either, except verbatim.

I don't think it constitutes a problem. In the long term they might force us to rename and re-logo but by being a open source, free, not-for-profit initiative, I don't think there's any risk. Also, I'm not a lawyer :D.

**Comment by sauloal** [comment]
@ypriverol , the 3 blocks with is their logo. Obviously I can modify it by hand :D

**Comment by sauloal** [comment]
@ypriverol ![logo](https://www.dropbox.com/s/9seobdxoum2kkpl/docker_logo_3.png?dl=1)

**Comment by sauloal** [comment]
@lgatto , i think letters of the DNA are better because protein letters are almost all letters

**Comment by ypriverol** [comment]
@sauloal I like this version the shortest one

**Comment by ypriverol** [comment]
@sauloal in any case is not so explicit in my opinion. Why do we need to keep the to keep the same docker icon?

**Comment by sauloal** [comment]
@ypriverol ... well.. ideas?

**Comment by Leprevost** [comment]
I like the idea of having the docker icon too because people can automatically spot that this has something to do with Docker. I saw other projects doing something similar

**Comment by sauloal** [comment]
/cc @BioDocker/contributors 
![no whale](https://www.dropbox.com/s/j2uwb744f1rmfrl/docker_logo_5.png?dl=1)

**Comment by sauloal** [comment]
![7](https://www.dropbox.com/s/giyt2syj8jx8was/docker_logo_7.png?dl=1)
![8](https://www.dropbox.com/s/eexqe5j0mnk7pha/docker_logo_8.png?dl=1)

**Comment by sauloal** [comment]
![6](https://www.dropbox.com/s/mggk6ozj8yvf4sq/docker_logo_6.png?dl=1)

**Comment by jvhaarst** [comment]
Saulo,

Wouldn't it be better if the containers were a bit more rectangular (to
make them more containers), and maybe just spell out "Bio" ?
Or make it a X-mas tree, that is also a bit more recognizable.

Dag,
Jan

On Tue, Sep 22, 2015 at 12:36 AM, Saulo <notifications@github.com> wrote:

> [image: 6]
> <https://camo.githubusercontent.com/d6e11bf8f88c6484c154fc8fe15c13150df93955/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f6d67676b366f7a6a387976663473712f646f636b65725f6c6f676f5f362e706e673f646c3d31>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BioDocker/biodocker/issues/33#issuecomment-142128898>.
>



-- 
Dag,
Jan

**Comment by sauloal** [comment]
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_02.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_03.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_05.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_06.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_07.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_08.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_09.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_10.png)
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_11.png)

**Comment by sauloal** [comment]
@jvhaarst  @ypriverol

**Comment by sauloal** [comment]
12
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_12.png)
13
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_13.png)
14
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_14.png)
15
![](https://dl.dropboxusercontent.com/u/753166/biodocker/docker_logo_15.png)

@BioDocker/contributors  @ypriverol  @Leprevost  @jvhaarst

**Comment by Leprevost** [comment]
hehe is that super Mario flower?
I like the three and the whale but I agree that both together is kinda weird.

**Comment by sauloal** [comment]
@Leprevost  yes :D

**Comment by rajido** [comment]
If BioDocker is going to become BioContainers as suggested in #59, would you consider a logo less biodockerised? Something like the image below. I would like something that could show we can have data and tools/code together in one (bio)container that can be easily reused.

![img_20160914_215221](https://cloud.githubusercontent.com/assets/2062396/18530160/1bcc35c6-7ac8-11e6-9f8f-2e29609107e3.jpg)
