### ISSUE TITLE
Should we have an extended dockerfile header and skip the readme ?

### ISSUE THREAD

**Issue by sauloal** [BioDocker/biodocker#36]
The last few days I've been busy creating new genomics packages in the sandbox and I came to a conclusion. 

Instead of having a README.md file for each container repeating the information that is already available in the header of the dockerfile, why not extend the header with more information and skip the readme?

The advantages are:
- you don't have to update the readme every time you update an package
- the header of a dockerfile is always synchronized with its own content
- if the header always follows the same format we can easily parse it
- we can create a "dynamic" (global) readme in the root of the repository containing the header of all dockerfiles present

i've created 2 more experimental fields in the header of the dockerfile: 
provides - list of provided programs (important if more than one)
tags - tags such as genomics, proteomics, etc

I propose to add more fields: 
software website: source website

/cc @BioDocker/contributors

**Comment by Leprevost** [comment]
we decided t the hangout meeting (Oct, 2) that the README files will be removed and the Dockerfile will be extended.

**Comment by bgruening** [comment]
Oo, there was a hangout meeting?

**Comment by sauloal** [comment]
@bgruening yes. we advertised it in gitter. is there a better way of contacting you? we should have such meetings every other week.
you can find the minutes of the meeting here:
https://docs.google.com/document/d/1pRLDhIAq5_tXaT0086zyJW0OfJAdVyNi0da-1VPpYqI/edit?usp=sharing

**Comment by bgruening** [comment]
I would prefer a new issue with the announcement. I think this is the most visible way to get people involved. I'm not following gitter yet. Yet another proprietary messaging service :(
Thanks, for the minutes!!!

**Comment by bgruening** [comment]
When is the next meeting. I would really like to talk to you guys :)

**Comment by ypriverol** [comment]
Next meeting was schedule in two weeks, next week. but please be aware that we can do weekly meetings if you want to advance an specific topic and you need the opinion of other members.

**Comment by Leprevost** [comment]
yes, we can schedule a weekly meeting as well.

**Comment by bgruening** [comment]
In two weeks is ok for me. Just wanted to discuss a few points and tell you what my plans are. We also have a master student that is eager to help us here (automatic container building and testing).

**Comment by ypriverol** [comment]
These are great news, if we add more people we will be able soon to growth. Then, lets talk next week.
