### ISSUE TITLE
USER biodocker do not have permission to access /data

### ISSUE THREAD

**Issue by Leprevost** [BioDocker/biodocker#37]
The /data/ folder set up as `WORKDIR` do not provide the biodocker user proper working permissions. I did some tests with the DIA_Umpire program and the software could not write the outputs on /data/. After removing the `USER biodocker` command, everything went back to normal.

**Comment by sauloal** [comment]
http://stackoverflow.com/questions/23544282/what-is-the-best-way-to-manage-permissions-for-docker-shared-volumes

RUN chown -R biodocker:biodocker /data /config

Also, change the UID/GID from 1001 to 1000 once it is the default ID to single user debian
