### ISSUE TITLE
BioDocker GUI

### ISSUE THREAD

**Issue by prvst** [BioDocker/biodocker#44]
I recently talked with someone interested in using Docker and our containers with proteomics tools. The person told me that the possibility of having a full pipeline or some complex-to-install,  ready-to-use  software is very interesting, but there is one point that makes things "little bit complicated", the CLI. The ideal scenario this person described me is something like a desktop icon where he can open a window and then just select one container from the list. that way he can have the container downloaded and installed for him.

I want to get your opinion on this, what do you guys @BioDocker/contributors think about it? Do we have such solution around somewhere?

**Comment by bgruening** [comment]
We are developing a Galaxy instance in Docker for protemomics and other areas (we call these Galaxy flavours): https://github.com/bgruening/docker-galaxyp

In combination with https://kitematic.com/ this is awesome. You have your desktop icon and just select one falvour one pipeline you want to run.
