### ISSUE TITLE
Docker is adopting Alpine Linux

### ISSUE THREAD

**Issue by prvst** [BioDocker/biodocker#46]
Docker announced this week that they are adopting Alpine Linux as their base image. (http://distrowatch.com/table.php?distribution=alpine). Besides making their images smaller, Alpine is designed towards better security. 
It's a cool decision but I don't think we should consider this, what do you think?

**Comment by sauloal** [comment]
I don't think we should use it either. most programs are tested in ubuntu. convert from one basesystem to another would be a major pain
