### ISSUE TITLE
biodocker and bioboxes

### ISSUE THREAD

**Issue by aliceminotto** [BioDocker/biodocker#48]
Hi,
is this project still active or did it migrate completely to bioboxes?
I was using the basic image from biodocker when I run into a discussion about merging the two project. They both have cool sides, but I'd prefer to stay with this at the moment, unless is abandoned...

Also if still active maybe in future have a talk about #44 ?

Cheers

**Comment by prvst** [comment]
Hi @aliceminotto ,
First of all, thanks for being interested in the project.

BioDocker and BioBoxes may seem alike but both projects have different goals. Our main objective is to provide standardized containers with bioinformatics software, also we are working hard to provide specifications and guidelines for creating new containers.

We are in constant work here, our project is **not** abandoned, besides the containers and specifications you see on our GitHub page, there is also a lot of discussion going on behind the scenes.

Please, feel free to join us and also feel free to post your requests, doubts and comments. This is a community project and we value the participation of everyone that is interested.

**Comment by aliceminotto** [comment]
@prvst Great to hear!!! 
Sorry, I couldn't actually guess the final thoughts from the related github issue. I actually think this project would suit better my purpose, just getting started, but hopefully something will come out soon(ish).

**Comment by prvst** [comment]
@aliceminotto I'm glad to hear that, please message me if you need any help.

Btw, about the #44, we are still figuring out how to work with this, if you are working on Windows or MAC, you may try [Docker Toolbox](https://www.docker.com/products/docker-toolbox). It contais a software called [Kitematic](https://kitematic.com/) that will provide you with a GUI to help manage your containers.
