### ISSUE TITLE
Upgrade base image

### ISSUE THREAD

**Issue by prvst** [BioDocker/biodocker#49]
I'm considering, as @julianu mentioned today, to upgrade the base image to the latest Ubuntu LTS version, 16.04. @BioDocker/contributors , any comments on that?

**Comment by julianu** [comment]
As I mentioned it, I obviously vote for doing this :+1:

**Comment by sauloal** [comment]
I would wait some 3 months just until the first patches come in.

**Comment by bgruening** [comment]
I also don't see an urgent need to upgrade.

**Comment by ypriverol** [comment]
@all I don't see the needs for the upgrade we have pending things such as the manuscript, the examples, the integration with other pipelines etc.

**Comment by prvst** [comment]
the upgrade will be in a couple of months
