### ISSUE TITLE
Travis failures

### ISSUE THREAD

**Issue by Leprevost** [BioDocker/biodocker#5]
I noticed that some repositories are failing in the Travis test. The docker images build correctly, the software inside works OK, and the DockerHub also reports no error. Investigating a little better I found that those repositories failed because Travis went out of space during the test, see below.

This is part of the log from Travis while building MSAmanda container:

    Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
    Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
    Untar re-exec error: exit status 1: output: write /usr/share/mime/packages/freedesktop.org.xml: no space left on device
    +echo 1
    +save_and_shutdown
    +'[' '!' -f /home/travis/build/BioDocker/MSAmanda/.exit_code ']'
    +set +e
    ++jobs -p
    +kill -9 104
    +halt -f
    [  390.840000] System halted.
    The command "./run 'docker build -t test 1.0.0.5242/.'" exited with 1.

**Comment by bgruening** [comment]
We can always try different services like https://circleci.com/docs/docker or https://www.shippable.com/. They are more specialised on Docker containers as far as I know.

**Comment by ypriverol** [comment]
@bgruening doing some checking I saw that https://circleci.com/pricing is free if we run only one containers at a time. One things of using  https://www.shippable.com/ is the API access for future developments. From user experience here some benchmark: http://www.slant.co/topics/186/compare/~circleci_vs_travis_vs_shippable. @Leprevost what about try circleci https://circleci.com/integrations/docker. @bgruening which system is Galaxy using. 

P.S @Leprevost we should use the new account biodockers@gmail.com

**Comment by bgruening** [comment]
@ypriverol The Galaxy Docker project is currently evaluating different solutions. No clear answer yet.
The Galaxy project is using Travis, Docker is here not needed.

**Comment by ypriverol** [comment]
Should we keep travis and we can move both togethers ...

**Comment by Leprevost** [comment]
@bgruening  hum, didnt hear about circleci, I will check that, thanks.

**Comment by ypriverol** [comment]
@Leprevost  can we start the integration with travis and specify the size need to run the tests and the run limitations?

**Comment by sauloal** [comment]
@Leprevost  & @ypriverol 
I've been digging. If we are setting webhooks to re-create the images upon commits and dockerhub will run the dockerfiles and report the result ( https://docs.docker.com/docker-hub/builds/#webhooks ). why do we need travis?

**Comment by Leprevost** [comment]
i still kinda new to travis, so i'm not sure about this. I checked some
forums and people are saying that this is a feature/bug from this service.
Well, we do use the automatic build system that checks the containers and
the images, i think that with travis we can add more tests to evaluate the
containers if we want to.

**Comment by sauloal** [comment]
@Leprevost , travis will spin a virtual machine and run a series of commands as defined in a travis file
dockerhub will sping a docker vm and run a series of commands as defined in a dockerfile file.

the only difference is the fact that travis email you. dockerhub can send you a HTTP post with the full log and result of running the dockerfile. if you dockerfile includes a series of tests, if a test fails the docker command fails.

that said, using travis implies that you will have to copy and adapt all the commands you have already tested in the dockerfile. I had huge problems adapting my program from ubuntu 14 to ubuntu 12 (different gcc versions).

**Comment by Leprevost** [comment]
do you think we can drop travis then?

**Comment by sauloal** [comment]
I think so. I can try to create a mock "travis to dockerhub"
