### ISSUE TITLE
Should we start using Quay.io ?

### ISSUE THREAD

**Issue by prvst** [BioDocker/biodocker#57]
Following @bgruening suggestions, I did some tests with Quay.io and it is really, much better than the native DockerHub service. So here are some points for us to consider:

Advantages
- Better API
- Faster (my test image was created and shipped within 10 minutes, compared to DockerHub that is taking from 2 to 6 hours)
- Better namespace (here we can have the biodocker namespace, instead of biodckr)

Disadvantages
- Looks that the build system is 'repository-centric', I'm not sure how to provide our containers with different versions. In DockerHub I create an Automated Build entry and inside I can specify every Dockerfile that is located on each folder.
- Looks like you need an account to use images from Quay.io (see below).

The good thing about this, @ypriverol @bgruening , is that I figured out how to use the native docker client to search and download images from quay.io ( you need to create an account at quay.io )

1.  `docker login quay.io`

2. `docker search quay.io/comet`   or `docker search quay.io/biodocker` 

simple as that!

**Comment by ypriverol** [comment]
@prvst As we decided we will push to both places dockerhub and the quay.io. I fully support that.

**Comment by prvst** [comment]
> @prvst As we decided we will push to both places dockerhub and the quay.io. I fully support that.

I remember, I just added this as a question to put everyone in context.

**Comment by prvst** [comment]
BTW @ypriverol , if we adopt both, how do we manage the namespace? keep using **biodckr** in Quay.io too?

**Comment by ypriverol** [comment]
Yes please is better for integration and understanding.

**Comment by prvst** [comment]
> Yes please is better for integration and understanding.
In any case, I got both under my user control, so we can protect the name.
