### ISSUE TITLE
Spin-off for geospatial community

### ISSUE THREAD

**Issue by nuest** [BioDocker/biodocker#58]
Hi there! Great project you have. Would you mind a spin-off for the "geo" community? I'd like to initiate something at https://github.com/GeoContainers that would be a total rip-off of your efforts here, which I would of course acknowledge! I'm just a party of one so far, but I'd like to re-use your processes etc hoping for external contributions in the near future. Would you mind me using your READMEs etc. as a template?

**Comment by prvst** [comment]
Hi @nuest.

First of all, I think that what you are trying to do is really cool, don't feel discouraged by been the only one so far, when I stated this project a few years ago I was the only one working, alone in the small hours.

Second, as the guy responsible for the initial idea of the project, I think I can speak for others when I say 'Yes, please!' Go ahead and feel free to use BioDocker as a model for your project. One of the ideas we have now is to maintain this as a open project and provide users and developers not only with containers but also with standards and guidelines.

Also, feel free to contact me directly if you need help or assistance with anything, I will be more that happy to help you.

**Comment by ypriverol** [comment]
Hi @nuest:
 It is a great idea to fork our project and structure to build your own community. Feel free to use 
 the complete infrastructure and ideas. We can thin in the future about posibilities to build an 
 strong collaboration. Keep us updated with the progress.
