### ISSUE TITLE
BioDocker vs BioContainers logo

### ISSUE THREAD

**Issue by rajido** [BioDocker/biodocker#61]
If BioDocker is going to become BioContainers as suggested in #59, would you consider a logo less biodockerised? Something like the image below. I would like something that could show we can have data and tools/code together in one (bio)container that can be easily reused.

![img_20160914_215221](https://cloud.githubusercontent.com/assets/2062396/18530160/1bcc35c6-7ac8-11e6-9f8f-2e29609107e3.jpg)

**Comment by ypriverol** [comment]
I like this prototype @rajido. Feel free to make and commit a digital version.

**Comment by rajido** [comment]
... first try. What do you think?
![biocontainers4](https://cloud.githubusercontent.com/assets/2062396/18818235/69e5ecbe-836c-11e6-8594-6730e503f38a.png)

**Comment by prvst** [comment]
@rajido , looks really nice

**Comment by ypriverol** [comment]
@rajido as we discuss I would like the version with this color: https://lh4.googleusercontent.com/-mNu08OCeyuE/AAAAAAAAAAI/AAAAAAAAAkA/cKNQGLamkAE/s0-c-k-no-ns/photo.jpg but just the logo you send me.

**Comment by rajido** [comment]
![biocontainers5](https://cloud.githubusercontent.com/assets/2062396/18851201/c8deaf82-8432-11e6-9e50-b026829fac01.png)
![biocontainers6](https://cloud.githubusercontent.com/assets/2062396/18851263/07dde8ec-8433-11e6-8f28-359cafae8d65.png)

[Adobe illustrator file](https://drive.google.com/file/d/0Bw_p-HKWUjHoUXZ3UFRxMnhHY1E/view?usp=sharing), [SVG file](https://drive.google.com/file/d/0Bw_p-HKWUjHobEo5V0VhNVhrdHc/view?usp=sharing)

**Comment by ypriverol** [comment]
@Rajido Can you upload the version with the same color in all the sides. The less intense orange

**Comment by rajido** [comment]
![biocontainers6 1](https://cloud.githubusercontent.com/assets/2062396/18885706/ab587562-84e4-11e6-9267-eb20def8e2f4.png)
![biocontainers6 2](https://cloud.githubusercontent.com/assets/2062396/18885751/edf256e0-84e4-11e6-881a-0366096b99bd.png)
![biocontainers6 3](https://cloud.githubusercontent.com/assets/2062396/18885752/edf3082e-84e4-11e6-95b5-ac8d2a0992b8.png)

**Comment by ypriverol** [comment]
@rajido you did a great job here. Thanks such much for this. If @sauloal is agree I would like to replace our old logo with this new one that is more verbose and explain more what is BioContainers.

**Comment by sauloal** [comment]
Im fine with that. Go for it. Great work

**Comment by ypriverol** [comment]
@rajido can you provide the svg of the logos.

**Comment by rajido** [comment]
[6.1 - svg](https://drive.google.com/file/d/0Bw_p-HKWUjHoOWNLSmlMOXI0bTQ/view?usp=sharing)
[6.2 - svg](https://drive.google.com/file/d/0Bw_p-HKWUjHoQkdIclhxTnViZzQ/view?usp=sharing)
[6.3 - svg](https://drive.google.com/file/d/0Bw_p-HKWUjHoMm1GVWFFRHZ0TVU/view?usp=sharing)
