### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by ypriverol** [BioDocker/biodocker#63]
Hi all:
 As I propose before I would like to re-brand BioDcoker to BioContainers and these two main reasons:

 - BioDcoker is fully attached with docker technologies when containers is a more broadly technology including everything that can be packages or distributed using containers. The best example is rkt   https://coreos.com/rkt/docs/latest/rkt-vs-other-projects.html. 
 
- BioDocker limited the contribution of other initiatives like mulled or conda packages to the community because they are not only docker based as I said in the first point. 

Please if any of you has complains or opinion about that is this the moment to give your opinion: @bgruening @sauloal @lgatto @julianu @hroest @timosachsenberg @prvst @avilella @hbarsnes @pcm32 @rajido @r78v10a07 @BioDocker/contributors 

Please if you are agree let me know and I can start the migration process.

**Comment by prvst** [comment]
I agree

**Comment by hroest** [comment]
there is also a legal reason: Since docker is a protected trademark, the company may start suing people that use docker in their name (it seems ok as our project does not start with docker):

https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle

**Comment by prvst** [comment]
regarding that we are safe, but i like the idea of rebranding

**Comment by hroest** [comment]
it is never really, really safe to use a trademarked name :-(

**Comment by ypriverol** [comment]
@BioDocker/contributors @BioDocker/owners Because more less everyone has agree to change the name I will close this issue and start the transition.

**Comment by timosachsenberg** [comment]
I agree
