### ISSUE TITLE
Spec for a unified data exchange volume

### ISSUE THREAD

**Issue by bgruening** [BioDocker/biodocker#9]
We need to agree on a spec for volumes.
Do we want to have separated volumes for input and output data? How should they be named?

**Comment by Leprevost** [comment]
I was thinking to use a wiki page explaining to people how to use the `-v` parameter to share directories with the containers. Check here what I did so far: https://github.com/BioDocker/specifications/wiki/Using-input--and-Output-files

**Comment by bgruening** [comment]
I like this a lot!
For me it's just not clear if you should use `data` or if you need to have two separated ones, for input and output. For example to mount in the inputs as `:ro`.

**Comment by Leprevost** [comment]
You only need a single folder to work with input and output files. In this case, the `data` folder is the internal folder, with `ro` permissions.

**Comment by bgruening** [comment]
But if you mix inputs and outputs it hard to guess which files needs to be copied/archived (the result ones).
For example if Galaxy mounts in 100 fastq files as `:ro`, it would be nice to know which files are result files.

**Comment by Leprevost** [comment]
i guess we could create sub folders inside `/data/`, like `/data/input` and `/data/output`

**Comment by bgruening** [comment]
@Leprevost who is responsible for creating these directories? I guess the host, because the host needs to mount files in as :ro?

**Comment by Leprevost** [comment]
for now I just thought to let this open for the user to define how to organize the directories, so instead of enforcing them on the specification I created that wiki explaining how to use it.

**Comment by sauloal** [comment]
I agree with leprevost on not making it strict but I also think that there's no harm to have a 'good practices' guide for the dockerfile maintainer such as 'whenever possible map your output folder as /data', 'if custom scripts/config files are needed, pre-setup them to use the /data folder', 'if config files are needed, make them available alongside the docker file and describe in the read.me file how to map them inside the VM to overlay the "default" config file"

**Comment by bgruening** [comment]
I would like to use these containers without reading a readme file. My aim is that it should be possible to run tools just with knowing some rules from BioDocker and the DockerHub image name. If I need to read a readme file before this is not very user-friendly.
Would be nice if we can archive this for many containers, either with strict rules or best-practice guidelines.

**Comment by sauloal** [comment]
@bgruening in a ideal world where all programs use an standard input standard I would agree with you. but I think a single rule is to restrictive. maybe create a set of rules to different patterns , updated whenever new patterns are encountered? 

I think the best "general" practice would to be able to run all the programs installed as if they were in your path. then you only need to run your docker + command + parameters. 

regarding the data, a helper script could call docker with -v $PWD:/data whenever you call a container.

biodocker container_name program_name parameters
which would call
docker run -v $PWD:/data biodocker/container_name program_name parameters

**Comment by Leprevost** [comment]
hum, maybe we could define something like this, maybe we could set a
specification for programs with single entry or option and a separate
specification for programs with more than one option. Not sure yet...

**Comment by sauloal** [comment]
fixed. i've added both to the best practices and dockerfile template

@Leprevost , could you close it?

**Comment by Leprevost** [comment]
thanks
